# Generated by Django 2.2.4 on 2019-08-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='wall', max_length=64)),
                ('movement_cost', models.IntegerField(default=0)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
            ],
        ),
    ]
