# Generated by Django 2.2.4 on 2019-08-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_cell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='type',
            new_name='kind',
        ),
    ]
